### ISSUE TITLE
Chat brakes when pressing middle mouse

### ISSUE THREAD

**Issue by konetprime** [destinygg/website#58]
Chrome, windows 7. When I use the scroll from pressing in the scroll wheel (not from spinning the wheel), the mouse cursor gets bugged and I can't click on anything. refreshing the tab doesn't fix this, the only way to do it is to kill the tab completely.

**Comment by hayksaakian** [comment]
can we fix this by handling the embeding server side instead of using an iframe?

or is that off the table?

**Comment by sztanpet** [comment]
no
yes

**Comment by cene-co-za** [comment]
The issue happens ONLY when the scrolling area is within an iframe.
You can see it here http://www.destiny.gg/embed/chat

Here showing the issue without any js libs / css etc.
http://jsfiddle.net/wqhyjpdz/1/


So we only have four options imo.
1. Not have the chat in an iframe.
2. Add js controls which override chrome
3. Disable middle mouse scroll in chrome
4. Do nothing.

Thoughts?

**Comment by hayksaakian** [comment]
Are there any down sides to 1? I'm unfamiliar with PHP so i can't claim it would be easy. But all you would do is render a view right?

I would assume that if all the sitewide javascript is compressed, minified and glued into one file that shouldn't be an issue.

The only down side i've thought of so far  is you would also need to be able to reload chat independently from the page (or maybe not? low priority?)

since this is a broweser issue, and destiny.gg isn't the only website using iframes, i'll look online to see if there's a fix that many people are using.

**Comment by sztanpet** [comment]
since most of the info is here, i shall reopen this

**Comment by xtphty** [comment]
Tested this via debugger, works for disabling the middle click: 

$('div.chat-output-frame').mousedown(function(e){if(e.button==1)return false});

This of course breaks the middle click scrolling behavior, if people complain about it that can be emulated using JS. 

Notes:
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
> 1: Auxiliary button pressed, usually the wheel button or themiddle button (if present)

**Comment by sztanpet** [comment]
https://code.google.com/p/chromium/issues/detail?id=336373 the upstream bug for it
